names = ["Rick Astley",
         "Shrek",
         "Jesus",
         "Dank Memer",
         "Mr Mosby",
         "Wendy",
         "Barry McKocner",
         "Jordan Peele",
         "Harry Balzac",
         "Kevin Hart",
         "Eda Dick",
         "Kim Jong Un",
         "Drake",
         "Kamala Harris",
         "Chris Peanuts",
         "A honey badger",
         "Discord Dog",
         "Rihanna",
         "Mr. Clean",
         "Satan",
         "ayylien",
         "Selena Gomez",
         "Harry",
         "Elizabeth Warren",
         "Dawn Keebals",
         "Billie Eyelash",
         "Joe Montana",
         "Mr. Ja-cough",
         "Your step-sister",
         "Dr. Phil",
         "Default Jonesy",
         "Cardi B",
         "Sans",
         "Peter Dinklage",
         "Nicki Minaj",
         "Dwight Shrute",
         "Timmy",
         "Donald Glover",
         "That fart you've been holding",
         "Paula Deen",
         "Lady Gaga",
         "Oprah",
         "Elon Musk",
         "Taylor Swift",
         "Melmsie's Beard",
         "Justin Bieber",
         "Toby Turner",
         "AirPod Jerk",
         "Your mom",
         "Mike Hoochie",
         "Mike Ock",
         "Spoopy Skelo",
         "Chungus",
         "Jennifer Lopez",
         "Barack Obama",
         "Cersei Lannister",
         "Carole Baskin",
         "Gordon Ramsay",
         "Thanos",
         "Emilia Clarke",
         "B Simpson",
         "Bongo cat",
         "Keanu Reeves",
         "Mr. Beast",
         "Annoying Ass Clown",
         "SierraSultan",
         "PaigeTelecanos",
         "Messi"]
loss_message = ["be gone thot",
                "all right thot be gone now",
                "coin.exe has stopped working",
                "I only give money to hookers",
                "go ask someone else",
                "I share money with no-one",
                "oh heck nah",
                "the atm is out of order, sorry",
                "bye jerk, no coins for you",
                "ew no",
                "Back in my day we worked for a living",
                "I would not share with the likes of you",
                "ew get away",
                "can you not",
                "nah, would rather not feed your gambling addiction",
                "I need my money to buy airpods",
                "You're too stanky",
                "Oh BAD-WORD nah",
                "stop begging",
                "Sure take this 'nonexistent' coin",
                "no coins for you",
                "there. is . no. coins. for. you.",
                "You get NOTHING!",
                "no u",
                "get lost u simp",
                "Get a job you hippy",
                "No way, you will just use it to buy pink phallics",
                "Good day rumpleforeskin!"]
